### ISSUE TITLE
NPE triggered because REPL context not cleaned up after tycking error

### ISSUE THREAD

**Issue by lunalunaa** [aya-prover/aya-dev#382]
To trigger this bug in REPL, type `data Nat =`, followed by `Nat`.

The context is not properly cleaned up after catching exception. This causes `Nat` in the next line of input to be resolved into a `Def`.

https://github.com/aya-prover/aya-dev/blob/5e56d11bfde25b7fb3c0bb2cad592b24bbf1958c/cli/src/main/java/org/aya/cli/repl/ReplCompiler.java#L143-L145

**Comment by ice1000** [comment]
I found a fix

**Comment by ice1000** [comment]
```
D:\git-repos\aya-prover [cp +0 ~1 -0 !]> D:\Java\Liberica-17-Full\bin\java.exe --enable-preview -jar .\cli\build\libs\cli-0.17-fat.jar -i -v=WARN
Aya 0.17 (e9e8371aab3aa28db012d6d33017511ae99aea15)
> data Nat =
In file <stdin>:1:9 ->

  1 | data Nat =
               ^^

Error: The name `=' is not defined in the current scope

> Nat
In file <stdin>:1:0 ->

  1 | Nat
      ^-^

Error: The name `Nat' is not defined in the current scope

> :q
See you space cow woof woof :3
```

Fixed! Oh yes!

**Comment by lunalunaa** [comment]
not fixed, see here: https://github.com/aya-prover/aya-dev/issues/381#issuecomment-1107433720

**Comment by imkiva** [comment]
![image](https://user-images.githubusercontent.com/9902643/165319068-06a99008-391c-45b3-ba81-15c709ea54e9.png)

Yes! I found a new fix!
